### ISSUE TITLE
接口问题

### ISSUE THREAD

**Issue by HZC-AND** [stone0090/OfficeTools.OnlineEditWord#4]
看了博主的接口文档，没有找到文档直接打印的接口，不知道是否有这样的接口？

**Comment by NebulaTechs** [comment]
js
wqmrjgerltjery

try
trjs
wqmrjgerltjery

try
tr
yrty
rt
y
rt
u
ty
u


ty
u
ty
u
y
t
yu
ty
u
tyjs
wqmrjgerltjery

try
tr
yrty
rt
y
rt
u
ty
u


ty
u
ty
u
y
t
yu
ty
u
tyjs
wqmrjgerltjery

try
tr
yrty
rt
y
rt
u
ty
u


ty
u
ty
u
y
t
yu
ty
u
tyjs
wqmrjgerltjery

try
tr
yrty
rt
y
rt
u
ty
u


ty
u
ty
u
y
t
yu
ty
u
tyjs
wqmrjgerltjery

try
tr
yrty
rt
y
rt
u
ty
u


ty
u
ty
u
y
t
yu
ty
u
tyjs
wqmrjgerltjery

try
tr
yrty
rt
y
rt
u
ty
u


ty
u
ty
u
y
t
yu
ty
u
tyjs
wqmrjgerltjery

try
tr
yrty
rt
y
rt
u
ty
u


ty
u
ty
u
y
t
yu
ty
u
tyjs
wqmrjgerltjery

try
tr
yrty
rt
y
rt
u
ty
u


ty
u
ty
u
y
t
yu
ty
u
tyjs
wqmrjgerltjery

try
tr
yrty
rt
y
rt
u
ty
u


ty
u
ty
u
y
t
yu
ty
u
tyjs
wqmrjgerltjery

try
tr
yrty
rt
y
rt
u
ty
u


ty
u
ty
u
y
t
yu
ty
u
tyjs
wqmrjgerltjery

try
tr
yrty
rt
y
rt
u
ty
u


ty
u
ty
u
y
t
yu
ty
u
tyjs
wqmrjgerltjery

try
tr
yrty
rt
y
rt
u
ty
u


ty
u
ty
u
y
t
yu
ty
u
tyjs
wqmrjgerltjery

try
tr
yrty
rt
y
rt
u
ty
u


ty
u
ty
u
y
t
yu
ty
u
tyjs
wqmrjgerltjery

try
tr
yrty
rt
y
rt
u
ty
u


ty
u
ty
u
y
t
yu
ty
u
tyjs
wqmrjgerltjery

try
tr
yrty
rt
y
rt
u
ty
u


ty
u
ty
u
y
t
yu
ty
u
tyjs
wqmrjgerltjery

try
tr
yrty
rt
y
rt
u
ty
u


ty
u
ty
u
y
t
yu
ty
u
tyjs
wqmrjgerltjery

try
tr
yrty
rt
y
rt
u
ty
u


ty
u
ty
u
y
t
yu
ty
u
tyjs
wqmrjgerltjery

try
tr
yrty
rt
y
rt
u
ty
u


ty
u
ty
u
y
t
yu
ty
u
tyjs
wqmrjgerltjery

try
tr
yrty
rt
y
rt
u
ty
u


ty
u
ty
u
y
t
yu
ty
u
tyjs
wqmrjgerltjery

try
tr
yrty
rt
y
rt
u
ty
u


ty
u
ty
u
y
t
yu
ty
u
tyjs
wqmrjgerltjery

try
tr
yrty
rt
y
rt
u
ty
u


ty
u
ty
u
y
t
yu
ty
u
tyjs
wqmrjgerltjery

try
tr
yrty
rt
y
rt
u
ty
u


ty
u
ty
u
y
t
yu
ty
u
tyjs
wqmrjgerltjery

try
tr
yrty
rt
y
rt
u
ty
u


ty
u
ty
u
y
t
yu
ty
u
tyjs
wqmrjgerltjery

try
tr
yrty
rt
y
rt
u
ty
u


ty
u
ty
u
y
t
yu
ty
u
tyjs
wqmrjgerltjery

try
tr
yrty
rt
y
rt
u
ty
u


ty
u
ty
u
y
t
yu
ty
u
tyjs
wqmrjgerltjery

try
tr
yrty
rt
y
rt
u
ty
u


ty
u
ty
u
y
t
yu
ty
u
tyjs
wqmrjgerltjery

try
tr
yrty
rt
y
rt
u
ty
u


ty
u
ty
u
y
t
yu
ty
u
tyjs
wqmrjgerltjery

try
tr
yrty
rt
y
rt
u
ty
u


ty
u
ty
u
y
t
yu
ty
u
tyjs
wqmrjgerltjery

try
tr
yrty
rt
y
rt
u
ty
u


ty
u
ty
u
y
t
yu
ty
u
tyjs
wqmrjgerltjery

try
tr
yrty
rt
y
rt
u
ty
u


ty
u
ty
u
y
t
yu
ty
u
tyjs
wqmrjgerltjery

try
tr
yrty
rt
y
rt
u
ty
u


ty
u
ty
u
y
t
yu
ty
u
tyjs
wqmrjgerltjery

try
tr
yrty
rt
y
rt
u
ty
u


ty
u
ty
u
y
t
yu
ty
u
tyjs
wqmrjgerltjery

try
tr
yrty
rt
y
rt
u
ty
u


ty
u
ty
u
y
t
yu
ty
u
tyjs
wqmrjgerltjery

try
tr
yrty
rt
y
rt
u
ty
u


ty
u
ty
u
y
t
yu
ty
u
tyjs
wqmrjgerltjery

try
tr
yrty
rt
y
rt
u
ty
u


ty
u
ty
u
y
t
yu
ty
u
tyjs
wqmrjgerltjery

try
tr
yrty
rt
y
rt
u
ty
u


ty
u
ty
u
y
t
yu
ty
u
tyjs
wqmrjgerltjery

try
tr
yrty
rt
y
rt
u
ty
u


ty
u
ty
u
y
t
yu
ty
u
tyjs
wqmrjgerltjery

try
tr
yrty
rt
y
rt
u
ty
u


ty
u
ty
u
y
t
yu
ty
u
tyjs
wqmrjgerltjery

try
tr
yrty
rt
y
rt
u
ty
u


ty
u
ty
u
y
t
yu
ty
u
tyjs
wqmrjgerltjery

try
tr
yrty
rt
y
rt
u
ty
u


ty
u
ty
u
y
t
yu
ty
u
tyjs
wqmrjgerltjery

try
tr
yrty
rt
y
rt
u
ty
u


ty
u
ty
u
y
t
yu
ty
u
tyjs
wqmrjgerltjery

try
tr
yrty
rt
y
rt
u
ty
u


ty
u
ty
u
y
t
yu
ty
u
tyjs
wqmrjgerltjery

try
tr
yrty
rt
y
rt
u
ty
u


ty
u
ty
u
y
t
yu
ty
u
tyjs
wqmrjgerltjery

try
tr
yrty
rt
y
rt
u
ty
u


ty
u
ty
u
y
t
yu
ty
u
tyjs
wqmrjgerltjery

try
tr
yrty
rt
y
rt
u
ty
u


ty
u
ty
u
y
t
yu
ty
u
tyjs
wqmrjgerltjery

try
tr
yrty
rt
y
rt
u
ty
u


ty
u
ty
u
y
t
yu
ty
u
tyjs
wqmrjgerltjery

try
tr
yrty
rt
y
rt
u
ty
u


ty
u
ty
u
y
t
yu
ty
u
tyjs
wqmrjgerltjery

try
tr
yrty
rt
y
rt
u
ty
u


ty
u
ty
u
y
t
yu
ty
u
tyjs
wqmrjgerltjery

try
tr
yrty
rt
y
rt
u
ty
u


ty
u
ty
u
y
t
yu
ty
u
tyjs
wqmrjgerltjery

try
tr
yrty
rt
y
rt
u
ty
u


ty
u
ty
u
y
t
yu
ty
u
tyjs
wqmrjgerltjery

try
tr
yrty
rt
y
rt
u
ty
u


ty
u
ty
u
y
t
yu
ty
u
tyjs
wqmrjgerltjery

try
tr
yrty
rt
y
rt
u
ty
u


ty
u
ty
u
y
t
yu
ty
u
tyjs
wqmrjgerltjery

try
tr
yrty
rt
y
rt
u
ty
u


ty
u
ty
u
y
t
yu
ty
u
tyjs
wqmrjgerltjery

try
tr
yrty
rt
y
rt
u
ty
u


ty
u
ty
u
y
t
yu
ty
u
tyjs
wqmrjgerltjery

try
tr
yrty
rt
y
rt
u
ty
u


ty
u
ty
u
y
t
yu
ty
u
tyjs
wqmrjgerltjery

try
tr
yrty
rt
y
rt
u
ty
u


ty
u
ty
u
y
t
yu
ty
u
tyjs
wqmrjgerltjery

try
tr
yrty
rt
y
rt
u
ty
u


ty
u
ty
u
y
t
yu
ty
u
tyjs
wqmrjgerltjery

try
tr
yrty
rt
y
rt
u
ty
u


ty
u
ty
u
y
t
yu
ty
u
tyjs
wqmrjgerltjery

try
tr
yrty
rt
y
rt
u
ty
u


ty
u
ty
u
y
t
yu
ty
u
tyjs
wqmrjgerltjery

try
tr
yrty
rt
y
rt
u
ty
u


ty
u
ty
u
y
t
yu
ty
u
ty
yrty
rt
y
rt
u
ty
u


ty
u
ty
u
y
t
yu
ty
u
ty
u
